### ISSUE TITLE
Error when trying to use initialize

### ISSUE THREAD

**Issue by grandmoffgigi** [camyosh/tablestuck#20]
Already tried reinstalling dependencies, it has admin permissions and everything in the file structure is where it should be. The only different is there is no package.json
```
failed when checking to see if someone is registered, or if they're over the tournament action limit.
C:\Users\Chungus' PC\Documents\Discord bot\tablestuck-master\commands\initialize.js:11
if(args[0].toLowerCase()!="confirm"){
           ^

TypeError: Cannot read property 'toLowerCase' of undefined
    at Object.exports.run (C:\Users\Chungus' PC\Documents\Discord bot\tablestuck-master\commands\initialize.js:11:12)
    at module.exports (C:\Users\Chungus' PC\Documents\Discord bot\tablestuck-master\events\message.js:56:7)
    at Client.emit (events.js:315:20)
    at MessageCreateAction.handle (C:\Users\Chungus' PC\Documents\Discord bot\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (C:\Users\Chungus' PC\Documents\Discord bot\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (C:\Users\Chungus' PC\Documents\Discord bot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (C:\Users\Chungus' PC\Documents\Discord bot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (C:\Users\Chungus' PC\Documents\Discord bot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10)
    at WebSocket.onMessage (C:\Users\Chungus' PC\Documents\Discord bot\node_modules\ws\lib\event-target.js:132:16)
    at WebSocket.emit (events.js:315:20)
```

**Comment by DocZane** [comment]
you know, I've had the fix to this sitting on my computer for 2 days just never pushed it. It's entirely my fault for missing a clause for the >initialize command, I'll push the fix in a bit. Thanks!
